<?php

/**
 * LICENSE: Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * PHP version 5
 *
 * @category  Microsoft
 * @package   WindowsAzure
 * @author    Azure PHP SDK <azurephpsdk@microsoft.com>
 * @copyright 2012 Microsoft Corporation
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 * @link      https://github.com/windowsazure/azure-sdk-for-php
 */

spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'windowsazure\\blob\\blobrestproxy' => '/Blob/BlobRestProxy.php',
            'windowsazure\\blob\\internal\\iblob' => '/Blob/Internal/IBlob.php',
            'windowsazure\\blob\\models\\accesscondition' => '/Blob/Models/AccessCondition.php',
            'windowsazure\\blob\\models\\accesspolicy' => '/Blob/Models/AccessPolicy.php',
            'windowsazure\\blob\\models\\acquireleaseoptions' => '/Blob/Models/AcquireLeaseOptions.php',
            'windowsazure\\blob\\models\\acquireleaseresult' => '/Blob/Models/AcquireLeaseResult.php',
            'windowsazure\\blob\\models\\blob' => '/Blob/Models/Blob.php',
            'windowsazure\\blob\\models\\blobblocktype' => '/Blob/Models/BlobBlockType.php',
            'windowsazure\\blob\\models\\blobprefix' => '/Blob/Models/BlobPrefix.php',
            'windowsazure\\blob\\models\\blobproperties' => '/Blob/Models/BlobProperties.php',
            'windowsazure\\blob\\models\\blobserviceoptions' => '/Blob/Models/BlobServiceOptions.php',
            'windowsazure\\blob\\models\\blobtype' => '/Blob/Models/BlobType.php',
            'windowsazure\\blob\\models\\block' => '/Blob/Models/Block.php',
            'windowsazure\\blob\\models\\blocklist' => '/Blob/Models/BlockList.php',
            'windowsazure\\blob\\models\\breakleaseresult' => '/Blob/Models/BreakLeaseResult.php',
            'windowsazure\\blob\\models\\commitblobblocksoptions' => '/Blob/Models/CommitBlobBlocksOptions.php',
            'windowsazure\\blob\\models\\container' => '/Blob/Models/Container.php',
            'windowsazure\\blob\\models\\containeracl' => '/Blob/Models/ContainerACL.php',
            'windowsazure\\blob\\models\\containerproperties' => '/Blob/Models/ContainerProperties.php',
            'windowsazure\\blob\\models\\copybloboptions' => '/Blob/Models/CopyBlobOptions.php',
            'windowsazure\\blob\\models\\copyblobresult' => '/Blob/Models/CopyBlobResult.php',
            'windowsazure\\blob\\models\\createblobblockoptions' => '/Blob/Models/CreateBlobBlockOptions.php',
            'windowsazure\\blob\\models\\createbloboptions' => '/Blob/Models/CreateBlobOptions.php',
            'windowsazure\\blob\\models\\createblobpagesoptions' => '/Blob/Models/CreateBlobPagesOptions.php',
            'windowsazure\\blob\\models\\createblobpagesresult' => '/Blob/Models/CreateBlobPagesResult.php',
            'windowsazure\\blob\\models\\createblobsnapshotoptions' => '/Blob/Models/CreateBlobSnapshotOptions.php',
            'windowsazure\\blob\\models\\createblobsnapshotresult' => '/Blob/Models/CreateBlobSnapshotResult.php',
            'windowsazure\\blob\\models\\createcontaineroptions' => '/Blob/Models/CreateContainerOptions.php',
            'windowsazure\\blob\\models\\deletebloboptions' => '/Blob/Models/DeleteBlobOptions.php',
            'windowsazure\\blob\\models\\deletecontaineroptions' => '/Blob/Models/DeleteContainerOptions.php',
            'windowsazure\\blob\\models\\getblobmetadataoptions' => '/Blob/Models/GetBlobMetadataOptions.php',
            'windowsazure\\blob\\models\\getblobmetadataresult' => '/Blob/Models/GetBlobMetadataResult.php',
            'windowsazure\\blob\\models\\getbloboptions' => '/Blob/Models/GetBlobOptions.php',
            'windowsazure\\blob\\models\\getblobpropertiesoptions' => '/Blob/Models/GetBlobPropertiesOptions.php',
            'windowsazure\\blob\\models\\getblobpropertiesresult' => '/Blob/Models/GetBlobPropertiesResult.php',
            'windowsazure\\blob\\models\\getblobresult' => '/Blob/Models/GetBlobResult.php',
            'windowsazure\\blob\\models\\getcontaineraclresult' => '/Blob/Models/GetContainerACLResult.php',
            'windowsazure\\blob\\models\\getcontainerpropertiesresult' => '/Blob/Models/GetContainerPropertiesResult.php',
            'windowsazure\\blob\\models\\leasemode' => '/Blob/Models/LeaseMode.php',
            'windowsazure\\blob\\models\\listblobblocksoptions' => '/Blob/Models/ListBlobBlocksOptions.php',
            'windowsazure\\blob\\models\\listblobblocksresult' => '/Blob/Models/ListBlobBlocksResult.php',
            'windowsazure\\blob\\models\\listblobsoptions' => '/Blob/Models/ListBlobsOptions.php',
            'windowsazure\\blob\\models\\listblobsresult' => '/Blob/Models/ListBlobsResult.php',
            'windowsazure\\blob\\models\\listcontainersoptions' => '/Blob/Models/ListContainersOptions.php',
            'windowsazure\\blob\\models\\listcontainersresult' => '/Blob/Models/ListContainersResult.php',
            'windowsazure\\blob\\models\\listpageblobrangesoptions' => '/Blob/Models/ListPageBlobRangesOptions.php',
            'windowsazure\\blob\\models\\listpageblobrangesresult' => '/Blob/Models/ListPageBlobRangesResult.php',
            'windowsazure\\blob\\models\\pagerange' => '/Blob/Models/PageRange.php',
            'windowsazure\\blob\\models\\pagewriteoption' => '/Blob/Models/PageWriteOption.php',
            'windowsazure\\blob\\models\\publicaccesstype' => '/Blob/Models/PublicAccessType.php',
            'windowsazure\\blob\\models\\setblobmetadataoptions' => '/Blob/Models/SetBlobMetadataOptions.php',
            'windowsazure\\blob\\models\\setblobmetadataresult' => '/Blob/Models/SetBlobMetadataResult.php',
            'windowsazure\\blob\\models\\setblobpropertiesoptions' => '/Blob/Models/SetBlobPropertiesOptions.php',
            'windowsazure\\blob\\models\\setblobpropertiesresult' => '/Blob/Models/SetBlobPropertiesResult.php',
            'windowsazure\\blob\\models\\setcontainermetadataoptions' => '/Blob/Models/SetContainerMetadataOptions.php',
            'windowsazure\\blob\\models\\signedidentifier' => '/Blob/Models/SignedIdentifier.php',
            'windowsazure\\common\\cloudconfigurationmanager' => '/Common/CloudConfigurationManager.php',
            'windowsazure\\common\\internal\\atom\\atombase' => '/Common/Internal/Atom/AtomBase.php',
            'windowsazure\\common\\internal\\atom\\atomlink' => '/Common/Internal/Atom/AtomLink.php',
            'windowsazure\\common\\internal\\atom\\category' => '/Common/Internal/Atom/Category.php',
            'windowsazure\\common\\internal\\atom\\content' => '/Common/Internal/Atom/Content.php',
            'windowsazure\\common\\internal\\atom\\entry' => '/Common/Internal/Atom/Entry.php',
            'windowsazure\\common\\internal\\atom\\feed' => '/Common/Internal/Atom/Feed.php',
            'windowsazure\\common\\internal\\atom\\generator' => '/Common/Internal/Atom/Generator.php',
            'windowsazure\\common\\internal\\atom\\person' => '/Common/Internal/Atom/Person.php',
            'windowsazure\\common\\internal\\atom\\source' => '/Common/Internal/Atom/Source.php',
            'windowsazure\\common\\internal\\authentication\\iauthscheme' => '/Common/Internal/Authentication/IAuthScheme.php',
            'windowsazure\\common\\internal\\authentication\\oauthscheme' => '/Common/Internal/Authentication/OAuthScheme.php',
            'windowsazure\\common\\internal\\authentication\\sharedkeyauthscheme' => '/Common/Internal/Authentication/SharedKeyAuthScheme.php',
            'windowsazure\\common\\internal\\authentication\\storageauthscheme' => '/Common/Internal/Authentication/StorageAuthScheme.php',
            'windowsazure\\common\\internal\\authentication\\tablesharedkeyliteauthscheme' => '/Common/Internal/Authentication/TableSharedKeyLiteAuthScheme.php',
            'windowsazure\\common\\internal\\connectionstringparser' => '/Common/Internal/ConnectionStringParser.php',
            'windowsazure\\common\\internal\\connectionstringsource' => '/Common/Internal/ConnectionStringSource.php',
            'windowsazure\\common\\internal\\filterableservice' => '/Common/Internal/FilterableService.php',
            'windowsazure\\common\\internal\\filters\\authenticationfilter' => '/Common/Internal/Filters/AuthenticationFilter.php',
            'windowsazure\\common\\internal\\filters\\datefilter' => '/Common/Internal/Filters/DateFilter.php',
            'windowsazure\\common\\internal\\filters\\exponentialretrypolicy' => '/Common/Internal/Filters/ExponentialRetryPolicy.php',
            'windowsazure\\common\\internal\\filters\\headersfilter' => '/Common/Internal/Filters/HeadersFilter.php',
            'windowsazure\\common\\internal\\filters\\retrypolicy' => '/Common/Internal/Filters/RetryPolicy.php',
            'windowsazure\\common\\internal\\filters\\retrypolicyfilter' => '/Common/Internal/Filters/RetryPolicyFilter.php',
            'windowsazure\\common\\internal\\filters\\wrapfilter' => '/Common/Internal/Filters/WrapFilter.php',
            'windowsazure\\common\\internal\\http\\batchrequest' => '/Common/Internal/Http/BatchRequest.php',
            'windowsazure\\common\\internal\\http\\batchresponse' => '/Common/Internal/Http/BatchResponse.php',
            'windowsazure\\common\\internal\\http\\httpcallcontext' => '/Common/Internal/Http/HttpCallContext.php',
            'windowsazure\\common\\internal\\http\\httpclient' => '/Common/Internal/Http/HttpClient.php',
            'windowsazure\\common\\internal\\http\\ihttpclient' => '/Common/Internal/Http/IHttpClient.php',
            'windowsazure\\common\\internal\\http\\iurl' => '/Common/Internal/Http/IUrl.php',
            'windowsazure\\common\\internal\\http\\url' => '/Common/Internal/Http/Url.php',
            'windowsazure\\common\\internal\\httpformatter' => '/Common/Internal/HttpFormatter.php',
            'windowsazure\\common\\internal\\invalidargumenttypeexception' => '/Common/Internal/InvalidArgumentTypeException.php',
            'windowsazure\\common\\internal\\iservicefilter' => '/Common/Internal/IServiceFilter.php',
            'windowsazure\\common\\internal\\logger' => '/Common/Internal/Logger.php',
            'windowsazure\\common\\internal\\mediaservicessettings' => '/Common/Internal/MediaServicesSettings.php',
            'windowsazure\\common\\internal\\oauthrestproxy' => '/Common/Internal/OAuthRestProxy.php',
            'windowsazure\\common\\internal\\parserstate' => '/Common/Internal/ConnectionStringParser.php',
            'windowsazure\\common\\internal\\resources' => '/Common/Internal/Resources.php',
            'windowsazure\\common\\internal\\restproxy' => '/Common/Internal/RestProxy.php',
            'windowsazure\\common\\internal\\serialization\\iserializer' => '/Common/Internal/Serialization/ISerializer.php',
            'windowsazure\\common\\internal\\serialization\\jsonserializer' => '/Common/Internal/Serialization/JsonSerializer.php',
            'windowsazure\\common\\internal\\serialization\\xmlserializer' => '/Common/Internal/Serialization/XmlSerializer.php',
            'windowsazure\\common\\internal\\servicebussettings' => '/Common/Internal/ServiceBusSettings.php',
            'windowsazure\\common\\internal\\servicemanagementsettings' => '/Common/Internal/ServiceManagementSettings.php',
            'windowsazure\\common\\internal\\servicerestproxy' => '/Common/Internal/ServiceRestProxy.php',
            'windowsazure\\common\\internal\\servicesettings' => '/Common/Internal/ServiceSettings.php',
            'windowsazure\\common\\internal\\storageservicesettings' => '/Common/Internal/StorageServiceSettings.php',
            'windowsazure\\common\\internal\\utilities' => '/Common/Internal/Utilities.php',
            'windowsazure\\common\\internal\\validate' => '/Common/Internal/Validate.php',
            'windowsazure\\common\\models\\getservicepropertiesresult' => '/Common/Models/GetServicePropertiesResult.php',
            'windowsazure\\common\\models\\logging' => '/Common/Models/Logging.php',
            'windowsazure\\common\\models\\metrics' => '/Common/Models/Metrics.php',
            'windowsazure\\common\\models\\oauthaccesstoken' => '/Common/Models/OAuthAccessToken.php',
            'windowsazure\\common\\models\\retentionpolicy' => '/Common/Models/RetentionPolicy.php',
            'windowsazure\\common\\models\\serviceproperties' => '/Common/Models/ServiceProperties.php',
            'windowsazure\\common\\serviceexception' => '/Common/ServiceException.php',
            'windowsazure\\common\\servicesbuilder' => '/Common/ServicesBuilder.php',
            'windowsazure\\queue\\internal\\iqueue' => '/Queue/Internal/IQueue.php',
            'windowsazure\\queue\\models\\createmessageoptions' => '/Queue/Models/CreateMessageOptions.php',
            'windowsazure\\queue\\models\\createqueueoptions' => '/Queue/Models/CreateQueueOptions.php',
            'windowsazure\\queue\\models\\getqueuemetadataresult' => '/Queue/Models/GetQueueMetadataResult.php',
            'windowsazure\\queue\\models\\listmessagesoptions' => '/Queue/Models/ListMessagesOptions.php',
            'windowsazure\\queue\\models\\listmessagesresult' => '/Queue/Models/ListMessagesResult.php',
            'windowsazure\\queue\\models\\listqueuesoptions' => '/Queue/Models/ListQueuesOptions.php',
            'windowsazure\\queue\\models\\listqueuesresult' => '/Queue/Models/ListQueuesResult.php',
            'windowsazure\\queue\\models\\peekmessagesoptions' => '/Queue/Models/PeekMessagesOptions.php',
            'windowsazure\\queue\\models\\peekmessagesresult' => '/Queue/Models/PeekMessagesResult.php',
            'windowsazure\\queue\\models\\queue' => '/Queue/Models/Queue.php',
            'windowsazure\\queue\\models\\queuemessage' => '/Queue/Models/QueueMessage.php',
            'windowsazure\\queue\\models\\queueserviceoptions' => '/Queue/Models/QueueServiceOptions.php',
            'windowsazure\\queue\\models\\updatemessageresult' => '/Queue/Models/UpdateMessageResult.php',
            'windowsazure\\queue\\models\\windowsazurequeuemessage' => '/Queue/Models/WindowsAzureQueueMessage.php',
            'windowsazure\\queue\\queuerestproxy' => '/Queue/QueueRestProxy.php',
            'windowsazure\\table\\internal\\atomreaderwriter' => '/Table/Internal/AtomReaderWriter.php',
            'windowsazure\\table\\internal\\iatomreaderwriter' => '/Table/Internal/IAtomReaderWriter.php',
            'windowsazure\\table\\internal\\imimereaderwriter' => '/Table/Internal/IMimeReaderWriter.php',
            'windowsazure\\table\\internal\\itable' => '/Table/Internal/ITable.php',
            'windowsazure\\table\\internal\\mimereaderwriter' => '/Table/Internal/MimeReaderWriter.php',
            'windowsazure\\table\\models\\batcherror' => '/Table/Models/BatchError.php',
            'windowsazure\\table\\models\\batchoperation' => '/Table/Models/BatchOperation.php',
            'windowsazure\\table\\models\\batchoperationparametername' => '/Table/Models/BatchOperationParameterName.php',
            'windowsazure\\table\\models\\batchoperations' => '/Table/Models/BatchOperations.php',
            'windowsazure\\table\\models\\batchoperationtype' => '/Table/Models/BatchOperationType.php',
            'windowsazure\\table\\models\\batchresult' => '/Table/Models/BatchResult.php',
            'windowsazure\\table\\models\\deleteentityoptions' => '/Table/Models/DeleteEntityOptions.php',
            'windowsazure\\table\\models\\edmtype' => '/Table/Models/EdmType.php',
            'windowsazure\\table\\models\\entity' => '/Table/Models/Entity.php',
            'windowsazure\\table\\models\\filters\\binaryfilter' => '/Table/Models/Filters/BinaryFilter.php',
            'windowsazure\\table\\models\\filters\\constantfilter' => '/Table/Models/Filters/ConstantFilter.php',
            'windowsazure\\table\\models\\filters\\filter' => '/Table/Models/Filters/Filter.php',
            'windowsazure\\table\\models\\filters\\propertynamefilter' => '/Table/Models/Filters/PropertyNameFilter.php',
            'windowsazure\\table\\models\\filters\\querystringfilter' => '/Table/Models/Filters/QueryStringFilter.php',
            'windowsazure\\table\\models\\filters\\unaryfilter' => '/Table/Models/Filters/UnaryFilter.php',
            'windowsazure\\table\\models\\getentityresult' => '/Table/Models/GetEntityResult.php',
            'windowsazure\\table\\models\\gettableresult' => '/Table/Models/GetTableResult.php',
            'windowsazure\\table\\models\\insertentityresult' => '/Table/Models/InsertEntityResult.php',
            'windowsazure\\table\\models\\property' => '/Table/Models/Property.php',
            'windowsazure\\table\\models\\query' => '/Table/Models/Query.php',
            'windowsazure\\table\\models\\queryentitiesoptions' => '/Table/Models/QueryEntitiesOptions.php',
            'windowsazure\\table\\models\\queryentitiesresult' => '/Table/Models/QueryEntitiesResult.php',
            'windowsazure\\table\\models\\querytablesoptions' => '/Table/Models/QueryTablesOptions.php',
            'windowsazure\\table\\models\\querytablesresult' => '/Table/Models/QueryTablesResult.php',
            'windowsazure\\table\\models\\tableserviceoptions' => '/Table/Models/TableServiceOptions.php',
            'windowsazure\\table\\models\\updateentityresult' => '/Table/Models/UpdateEntityResult.php',
            'windowsazure\\table\\tablerestproxy' => '/Table/TableRestProxy.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
